"""Project Ledger agent-facing substrate contracts."""

COMPILER_VERSION = "0.2.0"
MANIFEST_SCHEMA_VERSION = "1.1.0"
OBSERVATION_SCHEMA_VERSION = "1.0.0"
COMPAT_FLAT_SCHEMA_VERSION = "0.1.0"
CANONICAL_PROJECT_SCHEMA_VERSION = "1.0.0"
IDENTITY_DECISION_SCHEMA_VERSION = "1.0.0"
REVIEW_QUEUE_SCHEMA_VERSION = "1.0.0"

__all__ = [
    "COMPILER_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "OBSERVATION_SCHEMA_VERSION",
    "COMPAT_FLAT_SCHEMA_VERSION",
    "CANONICAL_PROJECT_SCHEMA_VERSION",
    "IDENTITY_DECISION_SCHEMA_VERSION",
    "REVIEW_QUEUE_SCHEMA_VERSION",
]
